/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Вход по логину и паролю. Access: Public.
         *     Успех → создаётся сессия, её id кладётся в httpOnly-cookie;
         *     возвращаем {message, user, company} (как в Welding Log, но без sessionID в теле).
         */
        post: operations["login_api_login__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Выход: удаляем сессию из БД (доступ пропадает мгновенно) и стираем cookie.
         */
        post: operations["logout_api_logout__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Текущий пользователь (по cookie сессии). Удобно для фронтенда.
         */
        get: operations["me_api_me__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Сменить свой пароль (нужен старый). Access: любой залогиненный.
         *     Снимает must_change_password. Другие сессии пользователя удаляются.
         */
        post: operations["change_password_api_user_change_password__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/password-reset/code/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Reset Code
         * @description Сгенерировать код сброса пароля (действует 15 минут). Access: privileged.
         *     master — для любого пользователя; admin/manager/site — только своей компании.
         *     Код показывается ОДИН раз — передай его человеку офлайн.
         */
        post: operations["create_reset_code_api_admin_password_reset_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Reset
         * @description Подтвердить код и установить новый пароль. Access: Public
         *     (человек не залогинен — он ведь забыл пароль). Код одноразовый.
         */
        post: operations["confirm_reset_api_user_password_reset_confirm__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate Password
         * @description Сгенерировать надёжный случайный пароль (удобно при создании пользователей).
         */
        get: operations["generate_password_api_generate_password__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Создать пользователя. Access: privileged.
         *     master — в любой компании (companyid обязателен); admin/manager/site — только в своей.
         *     Роль master может выдать только master. Ответ содержит временный пароль (один раз).
         */
        post: operations["create_user_api_user__post"];
        /**
         * Delete User
         * @description Удалить пользователя НАСОВСЕМ (GDPR: сессии, коды сброса, позже — прогресс).
         *     Access: privileged (в рамках своей компании; master — везде).
         *     Нельзя удалить себя и последнего master.
         */
        delete: operations["delete_user_api_user__delete"];
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Обновить пользователя. Access: своя запись (имя/email/логин) или privileged.
         *     Смена роли — только privileged; свою роль менять нельзя;
         *     выдать/забрать master может только master.
         */
        patch: operations["update_user_api_user__patch"];
        trace?: never;
    };
    "/api/user/lock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock User
         * @description Заблокировать/разблокировать. Access: privileged (в рамках компании).
         *     Блокировка мгновенно гасит все сессии пользователя. Себя блокировать нельзя.
         */
        post: operations["lock_user_api_user_lock__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Один пользователь. Access: своя запись или privileged (в рамках компании).
         */
        get: operations["get_user_api_user__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Список пользователей. Access: privileged.
         *     master видит всех (можно фильтровать ?companyid=); остальные — только свою компанию.
         */
        get: operations["list_users_api_users__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Company
         * @description Создать компанию-клиента. Access: master.
         */
        post: operations["create_company_api_company__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Все компании. Access: master.
         */
        get: operations["list_companies_api_companies__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/company/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Company
         * @description Своя компания. Access: любой залогиненный (как в Welding Log).
         */
        get: operations["my_company_api_user_company__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accept_privacy_policy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Privacy Policy
         * @description Зафиксировать согласие с текущей версией Privacy Policy.
         */
        post: operations["accept_privacy_policy_api_accept_privacy_policy__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accept_terms_and_conditions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Terms
         * @description Зафиксировать согласие с текущей версией Terms & Conditions.
         */
        post: operations["accept_terms_api_accept_terms_and_conditions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Category
         * @description Создать категорию/подкатегорию. Access: master.
         */
        post: operations["create_category_api_category__post"];
        /**
         * Delete Category
         * @description Удалить пустую категорию (без подкатегорий и уроков). Access: master.
         */
        delete: operations["delete_category_api_category__delete"];
        options?: never;
        head?: never;
        /**
         * Update Category
         * @description Обновить категорию (имя/порядок). Access: master.
         */
        patch: operations["update_category_api_category__patch"];
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Дерево категорий (два уровня). Access: любой залогиненный.
         *     Рабочие видят только категории, где есть доступные им уроки;
         *     привилегированные/master — все категории.
         */
        get: operations["list_categories_api_categories__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Lesson
         * @description Создать урок и задать видимость (roles / is_public). Access: master.
         */
        post: operations["create_lesson_api_lesson__post"];
        /**
         * Delete Lesson
         * @description Удалить урок. Access: master.
         */
        delete: operations["delete_lesson_api_lesson__delete"];
        options?: never;
        head?: never;
        /**
         * Update Lesson
         * @description Обновить урок (в т.ч. видимость). Access: master.
         */
        patch: operations["update_lesson_api_lesson__patch"];
        trace?: never;
    };
    "/api/lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lessons
         * @description Каталог видимых пользователю уроков (краткие карточки). Access: залогиненный.
         */
        get: operations["list_lessons_api_lessons__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson
         * @description Полный урок (для плеера). Access: залогиненный, если урок ему виден.
         */
        get: operations["get_lesson_api_lesson__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Progress
         * @description Весь мой прогресс.
         */
        get: operations["my_progress_api_progress__get"];
        put?: never;
        /**
         * Save Progress
         * @description Автосохранение прогресса по уроку. Только для видимых пользователю уроков.
         */
        post: operations["save_progress_api_progress__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Progress For Lesson
         * @description Мой прогресс по конкретному уроку (для возобновления с последней позиции).
         */
        get: operations["my_progress_for_lesson_api_progress__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Reports
         * @description Личная статистика обучения (по видимым мне урокам).
         */
        get: operations["my_reports_api_reports__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Dashboard
         * @description Данные для главной: прогресс в шапке + ряды continue/recommended/recently.
         */
        get: operations["my_dashboard_api_dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roles
         * @description Список всех ролей.
         */
        get: operations["get_roles_api_roles__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Master Dashboard
         * @description Сводка «здоровья платформы». Access: master.
         */
        get: operations["master_dashboard_api_master_dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Корневой эндпоинт — просто отвечает, что API работает.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Проверка, что сервер жив (не трогает БД).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Db
         * @description Проверка, что бэкенд видит базу данных.
         *     Выполняет простейший запрос SELECT 1.
         */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityBlock
         * @description Блок «Активность» — только анонимные агрегаты по всей платформе.
         */
        ActivityBlock: {
            /** Online Now */
            online_now: number;
            /** Completions Total */
            completions_total: number;
            /** Top Lessons */
            top_lessons: components["schemas"]["TopLesson"][];
        };
        /**
         * CategoryCreateIn
         * @description POST /api/category/ — создать (master). parent_id=None → верхний уровень.
         */
        CategoryCreateIn: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /**
         * CategoryOut
         * @description Категория без вложенности (используется как узел дерева).
         */
        CategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id: number | null;
            /** Order */
            order: number;
        };
        /**
         * CategoryTreeOut
         * @description Категория верхнего уровня со списком подкатегорий.
         */
        CategoryTreeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id: number | null;
            /** Order */
            order: number;
            /**
             * Subcategories
             * @default []
             */
            subcategories: components["schemas"]["CategoryOut"][];
        };
        /**
         * CategoryUpdateIn
         * @description PATCH /api/category/ — обновить (master). Меняется только переданное.
         */
        CategoryUpdateIn: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
        };
        /**
         * ChangePasswordIn
         * @description POST /api/user/change-password/ — смена своего пароля.
         */
        ChangePasswordIn: {
            /** Old Pw */
            old_pw: string;
            /** New Pw */
            new_pw: string;
        };
        /**
         * CompaniesBlock
         * @description Блок «Компании».
         */
        CompaniesBlock: {
            /** Total */
            total: number;
            /** Locked */
            locked: number;
        };
        /**
         * CompanyCreateIn
         * @description POST /api/company/ — создать компанию-клиента (только master).
         */
        CompanyCreateIn: {
            /** Name */
            name: string;
            /** Businessid */
            businessid?: string | null;
            /** Email */
            email?: string | null;
        };
        /** CompanyOut */
        CompanyOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Businessid */
            businessid?: string | null;
            /** Email */
            email?: string | null;
            /** Is Locked */
            is_locked: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Users Count */
            users_count: number;
        };
        /**
         * ContentBlock
         * @description Блок «Контент» — каталог общий для всех компаний.
         */
        ContentBlock: {
            /** Categories */
            categories: number;
            /** Lessons */
            lessons: number;
            /** Public Lessons */
            public_lessons: number;
        };
        /**
         * DashboardOut
         * @description GET /api/dashboard/ — данные для главной.
         */
        DashboardOut: {
            summary: components["schemas"]["ProgressSummary"];
            /** Continue Learning */
            continue_learning: components["schemas"]["LessonWithStatus"][];
            /** Recommended */
            recommended: components["schemas"]["LessonWithStatus"][];
            /** Recently Watched */
            recently_watched: components["schemas"]["LessonWithStatus"][];
            /** Is New User */
            is_new_user: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LessonCardOut
         * @description Краткая карточка урока для каталога (без транскрипта).
         */
        LessonCardOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Category Id */
            category_id: number;
            /** Order */
            order: number;
        };
        /**
         * LessonCreateIn
         * @description POST /api/lesson/ — создать урок (master).
         */
        LessonCreateIn: {
            /** Title */
            title: string;
            /** Vimeo Id */
            vimeo_id: string;
            /** Category Id */
            category_id: number;
            /** Description */
            description?: string | null;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Transcript */
            transcript?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
            /**
             * Roles
             * @default []
             */
            roles: string[];
        };
        /**
         * LessonOut
         * @description Полный урок (для плеера и для master): с транскриптом и видимостью.
         */
        LessonOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            /** Vimeo Id */
            vimeo_id: string;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Transcript */
            transcript: string | null;
            /** Category Id */
            category_id: number;
            /** Is Public */
            is_public: boolean;
            /** Order */
            order: number;
            /** Roles */
            roles: string[];
        };
        /**
         * LessonUpdateIn
         * @description PATCH /api/lesson/ — обновить урок (master). Меняется только переданное.
         *     roles=None — не трогать видимость; roles=[] — очистить список ролей.
         */
        LessonUpdateIn: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Vimeo Id */
            vimeo_id?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Transcript */
            transcript?: string | null;
            /** Order */
            order?: number | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Roles */
            roles?: string[] | null;
        };
        /**
         * LessonWithStatus
         * @description Карточка урока + статус прохождения текущим пользователем.
         */
        LessonWithStatus: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Category Id */
            category_id: number;
            /** Order */
            order: number;
            /** Status */
            status: string;
            /** Watch Percent */
            watch_percent: number;
        };
        /**
         * LoginIn
         * @description Тело запроса POST /api/login/ (пароль — в теле, не в URL).
         */
        LoginIn: {
            /** Un */
            un: string;
            /** Pw */
            pw: string;
        };
        /**
         * LoginOut
         * @description Ответ POST /api/login/ — форма как в Welding Log ({message, user, company}),
         *     но БЕЗ sessionID в теле: сессия уезжает в httpOnly-cookie.
         */
        LoginOut: {
            /**
             * Message
             * @default OK
             */
            message: string;
            user: components["schemas"]["UserOut"];
            company: components["schemas"]["CompanyOut"];
        };
        /**
         * MasterDashboardOut
         * @description GET /api/master/dashboard/ — сводка платформы для master.
         */
        MasterDashboardOut: {
            companies: components["schemas"]["CompaniesBlock"];
            users: components["schemas"]["UsersBlock"];
            content: components["schemas"]["ContentBlock"];
            activity: components["schemas"]["ActivityBlock"];
            recent: components["schemas"]["RecentBlock"];
        };
        /** ProgressOut */
        ProgressOut: {
            /** Lesson Id */
            lesson_id: number;
            /** Status */
            status: string;
            /** Watch Percent */
            watch_percent: number;
            /** Last Position Seconds */
            last_position_seconds: number;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * ProgressSaveIn
         * @description POST /api/progress/ — автосохранение прогресса (плеер шлёт периодически).
         *     Статус вычисляется автоматически по watch_percent (см. progress_service).
         */
        ProgressSaveIn: {
            /** Lesson Id */
            lesson_id: number;
            /** Watch Percent */
            watch_percent: number;
            /**
             * Last Position Seconds
             * @default 0
             */
            last_position_seconds: number;
        };
        /**
         * ProgressSummary
         * @description Сводка по прогрессу (для Reports и шапки Dashboard).
         */
        ProgressSummary: {
            /** Total Visible */
            total_visible: number;
            /** Completed */
            completed: number;
            /** In Progress */
            in_progress: number;
            /** Not Started */
            not_started: number;
            /** Completion Percent */
            completion_percent: number;
        };
        /**
         * RecentBlock
         * @description Блок «Недавнее» — последние созданные компании и пользователи.
         */
        RecentBlock: {
            /** Companies */
            companies: components["schemas"]["RecentCompany"][];
            /** Users */
            users: components["schemas"]["RecentUser"][];
        };
        /**
         * RecentCompany
         * @description Недавно созданная компания.
         */
        RecentCompany: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RecentUser
         * @description Недавно созданный пользователь.
         */
        RecentUser: {
            /** Id */
            id: number;
            /** Un */
            un: string;
            /** Name */
            name: string;
            /** Company Name */
            company_name: string;
            /** Role Key */
            role_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportsOut
         * @description GET /api/reports/ — личная статистика.
         */
        ReportsOut: {
            summary: components["schemas"]["ProgressSummary"];
            /** Lessons */
            lessons: components["schemas"]["LessonWithStatus"][];
        };
        /**
         * ResetCodeOut
         * @description Ответ: код показываем ОДИН раз (дальше храним только хеш).
         */
        ResetCodeOut: {
            /** Un */
            un: string;
            /** Code */
            code: string;
            /** Expires Minutes */
            expires_minutes: number;
        };
        /**
         * ResetCodeRequestIn
         * @description POST /api/admin/password-reset/code/ — админ просит код для пользователя.
         */
        ResetCodeRequestIn: {
            /** Un */
            un: string;
        };
        /**
         * ResetConfirmIn
         * @description POST /api/user/password-reset/confirm/ — пользователь вводит код и новый пароль.
         */
        ResetConfirmIn: {
            /** Un */
            un: string;
            /** Code */
            code: string;
            /** New Pw */
            new_pw: string;
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Is Privileged */
            is_privileged: boolean;
        };
        /**
         * TopLesson
         * @description Урок в топе по числу завершений.
         */
        TopLesson: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Completions */
            completions: number;
        };
        /**
         * UserCreateIn
         * @description POST /api/user/ — создать пользователя. Пароль не передаётся:
         *     система сама генерирует временный и возвращает его один раз.
         */
        UserCreateIn: {
            /** Un */
            un: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Email */
            email?: string | null;
            /** Companyid */
            companyid?: number | null;
        };
        /**
         * UserCreateOut
         * @description Ответ на создание: пользователь + временный пароль (показывается один раз).
         */
        UserCreateOut: {
            user: components["schemas"]["UserOut"];
            /** Temp Password */
            temp_password: string;
        };
        /**
         * UserDeleteIn
         * @description DELETE /api/user/ — удалить пользователя (GDPR: данные стираются насовсем).
         */
        UserDeleteIn: {
            /** Un */
            un: string;
        };
        /**
         * UserLockIn
         * @description POST /api/user/lock/ — заблокировать (true) или разблокировать (false).
         */
        UserLockIn: {
            /** Un */
            un: string;
            /** Locked */
            locked: boolean;
        };
        /**
         * UserOut
         * @description Пользователь в ответе API (форма как у Welding Log).
         */
        UserOut: {
            /** Id */
            id: number;
            /** Un */
            un: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Companyid */
            companyid: number;
            /** Privileges */
            privileges: {
                [key: string]: number;
            };
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Pending Consents
             * @default []
             */
            pending_consents: string[];
        };
        /**
         * UserUpdateIn
         * @description PATCH /api/user/ — обновить пользователя. un указывает, КОГО меняем;
         *     остальные поля необязательны — меняется только то, что передано.
         */
        UserUpdateIn: {
            /** Un */
            un: string;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** New Un */
            new_un?: string | null;
            /** Role */
            role?: string | null;
        };
        /**
         * UsersBlock
         * @description Блок «Пользователи».
         */
        UsersBlock: {
            /** Total */
            total: number;
            /** Locked */
            locked: number;
            /** Pending First Login */
            pending_first_login: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_api_me__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_user_change_password__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reset_code_api_admin_password_reset_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetCodeRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetCodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_reset_api_user_password_reset_confirm__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_password_api_generate_password__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_user__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_user__delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDeleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_user__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_user_api_user_lock__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_user__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users__get: {
        parameters: {
            query?: {
                /** @description master: фильтр по компании */
                companyid?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_api_company__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_companies__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_company_api_user_company__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_privacy_policy_api_accept_privacy_policy__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_terms_api_accept_terms_and_conditions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_category__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_category__delete: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_category__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTreeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_api_lesson__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lesson_api_lesson__delete: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesson_api_lesson__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_api_lessons__get: {
        parameters: {
            query?: {
                /** @description фильтр по категории */
                category_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_lesson__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_progress_api_progress__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_progress_api_progress__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressSaveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_progress_for_lesson_api_progress__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_reports_api_reports__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_dashboard_api_dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roles_api_roles__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
        };
    };
    master_dashboard_api_master_dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterDashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
